# Generated by Django 4.2 on 2025-04-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('account', '0002_budgethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_history', to='category.category'),
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_history', to='category.expense'),
        ),
        migrations.AlterField(
            model_name='accountbudget',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
