# Generated by Django 4.2 on 2025-04-14 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_budgethistory_category_budgethistory_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgethistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
